# Generated by Django 4.2.1 on 2023-05-13 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('idarea', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('idsede', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('documento', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('tipodocumento', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=80)),
                ('apellidos', models.CharField(max_length=80)),
                ('area', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('usuario', models.CharField(max_length=100)),
                ('contraseña', models.CharField(max_length=100)),
                ('idarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SoporteTecnico.area')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='idsede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SoporteTecnico.sede'),
        ),
    ]
