# Generated by Django 4.2.1 on 2023-05-16 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SoporteTecnico', '0002_alter_usuario_area_alter_usuario_idarea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='area',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='idarea',
        ),
    ]
