# Generated by Django 4.2.1 on 2023-05-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoporteTecnico', '0003_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='nombrearea',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='nombrepersona',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
