# Generated by Django 4.2.1 on 2023-05-17 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SoporteTecnico', '0004_alter_usuario_apellidos_alter_usuario_nombres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('resuelto', models.BooleanField(default=False)),
                ('idarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SoporteTecnico.area')),
            ],
        ),
    ]
